import { AlertTriangle, CheckCircle2, Scale } from 'lucide-react';
import { setRequestLocale } from 'next-intl/server';

import PageHero from '@/components/PageHero';
import { Link } from '@/i18n/navigation';
import { buildLocalizedPageMetadata } from '@/lib/site';

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  return buildLocalizedPageMetadata({
    locale,
    path: '/terms',
    titleKey: 'terms.title',
    descriptionKey: 'terms.subtitle',
  });
}

export default async function TermsPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  setRequestLocale(locale);

  return (
    <div className="bg-[var(--bg-primary)] min-h-screen pb-20">
      <PageHero
        badge="Terms of Service"
        badgeIcon={Scale}
        title="Simple, Developer-Friendly Terms"
        subtitle="PDFWritter is a free web utility. Read our usage guidelines and disclaimer rules below."
        accentColor="var(--accent)"
        glowColor="rgba(59, 130, 246, 0.08)"
      />

      <div className="page-container max-w-3xl mt-12 sm:mt-16">
        <div className="prose prose-invert max-w-none space-y-10 text-[var(--text-secondary)]">
          
          {/* Main Statement */}
          <section className="bg-[var(--bg-secondary)]/50 border border-[var(--border-color)] rounded-2xl p-6 sm:p-8 backdrop-blur-sm">
            <div className="flex gap-4 items-start">
              <div className="w-10 h-10 rounded-xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center shrink-0">
                <CheckCircle2 className="w-5 h-5 text-blue-500" />
              </div>
              <div>
                <h2 className="text-lg font-bold text-[var(--text-primary)] mb-2">Free for Any Use</h2>
                <p className="text-sm leading-relaxed">
                  PDFWritter is open source, free to use, and has no hidden limits, premium paywalls, or usage restriction quotas. You can use it for personal, commercial, or academic documents without attribution requirements.
                </p>
              </div>
            </div>
          </section>

          {/* Guidelines */}
          <section className="space-y-6">
            <h2 className="text-xl font-extrabold text-[var(--text-primary)] border-b border-[var(--border-color)] pb-3">
              1. Ownership of Content
            </h2>
            <p className="text-sm leading-relaxed">
              We do not claim any intellectual property rights or ownership over the files, text, images, or code templates you load, edit, or convert within PDFWritter. Any output file (.pdf, .html, .txt) generated by the tool is exclusively yours.
            </p>
          </section>

          <section className="space-y-6">
            <h2 className="text-xl font-extrabold text-[var(--text-primary)] border-b border-[var(--border-color)] pb-3">
              2. Acceptable Use
            </h2>
            <p className="text-sm leading-relaxed">
              Since conversions happen client-side in your own browser, you are solely responsible for compliance with any laws, corporate guidelines, or regulations governing the data you write, preview, or download on your machine.
            </p>
          </section>

          <section className="space-y-6 bg-amber-500/5 border border-amber-500/10 rounded-2xl p-6">
            <div className="flex gap-3">
              <AlertTriangle className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
              <div>
                <h3 className="text-sm font-bold text-[var(--text-primary)] mb-2">3. Warranty Disclaimer (&ldquo;As Is&rdquo;)</h3>
                <p className="text-xs leading-relaxed text-[var(--text-secondary)]">
                  PDFWritter is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranty of any kind, express or implied. We do not warrant that the application will be uninterrupted, error-free, or meet all markdown syntax conversion requirements perfectly. Because data is stored in the browser, you are responsible for maintaining backups of your source files.
                </p>
              </div>
            </div>
          </section>

          <section className="space-y-6">
            <h2 className="text-xl font-extrabold text-[var(--text-primary)] border-b border-[var(--border-color)] pb-3">
              4. Service Availability
            </h2>
            <p className="text-sm leading-relaxed">
              We reserve the right to modify, compile new features, or take the site offline momentarily for standard build deployments.
            </p>
          </section>

          {/* Contact Section */}
          <div className="pt-8 border-t border-[var(--border-color)] text-xs text-center text-[var(--text-tertiary)]">
            If you have questions regarding these terms, please use our{' '}
            <Link href="/contact" className="text-[#6366f1] hover:underline">
              contact form
            </Link>
            .
          </div>

        </div>
      </div>
    </div>
  );
}
